name: Deploy Package

on:
  workflow_dispatch:
    inputs:
      level:
        description: "The level of release to make"
        required: true
        type: choice
        default: "patch"
        options:
          - "patch"
          - "minor"
          - "major"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: |
          npm install
          npm install -g vsce
          npm install -g ovsx

      - name: Set up git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Package
        run: vsce package ${{ inputs.level }}

      - name: Deploy to VSMarketplace
        run: vsce publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}

      - name: Deploy to Open VSX
        run: ovsx publish -p ${{ secrets.OPEN_VSX_TOKEN }}

      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
